data:
  FUNCTIONS_WORKER_RUNTIME: Tm9uZQ==
apiVersion: v1
kind: Secret
metadata:
  name: neighborly-api
---
data:
  host.master: VzAxbzQ4VWFEQlJnVFJMaVAvMFFLQXhwZ01zdjlFOEFuSWJyUXJhZDNXSFc1UHNwb2YwSldRPT0=
  host.function.default: bjF6cTJSdWY3WDZkQUNkM0NPbGppcGhpTHNWMDk0WnY2OGNZQlFDMi9KM2x1eExBZmZ1cWdBPT0=
  host.systemKey.default: RmdxSWppNXQ0a2g2NE0vWTBlRFNaTmo1UWpxc3NYSFphcEI4MnZkWWE3aGlLYTRFRGRDa29nPT0=
  functions.createadvertisement.default: UU9kUGRpZmdmYjFnSm1PeDBIQXRoMk5TSEkwV281NXpRM2FTNFBCNGF5YUdDaExHaUtCdTFBPT0=
  functions.deleteadvertisement.default: OHNRaEFaMkNyYTFYd01vUS9LZk53TkhyRnFKc2FpeEFtMGxucDN6dFlmV1RHRFg2QzhYY2xBPT0=
  functions.getadvertisement.default: N2tRd1N2VlFCbUMydGFUTHVqVWo2ZlBqeTJSbmEzYm9rQWN5dXhORUJQWVplNWdZSmVrVVZ3PT0=
  functions.getadvertisements.default: Z1JrQ2haTDZrRDFhNVFDVHhyYXFicnh4aHpCdmJoOXc1YndmTmNvaEk4bGVhOGpIU0hpODN3PT0=
  functions.getpost.default: cWFDOGNhQVBzZzBlT1FYZEdScnRXeE9zRlVJSTR5dTQ2STh1czljeDNtS0R6d2k4dDZOQmxRPT0=
  functions.getposts.default: Yk1IMVNQY2IvNnJwaFJ4ekczSlRCT0lmTTVRYmtVaElGQXowRTNwSzdxRWJ0UFlhREVnai93PT0=
  functions.updateadvertisement.default: MTFLZ1V2ajNQTkhRaE5ISWN1YS81ZWQ3S0JjNkVjVTJBWFVCbzc0dG9lZGEwSWxrUEh2TWRRPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-neighborly-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neighborly-api-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: neighborly-api-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neighborly-api-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: neighborly-api-http
spec:
  selector:
    app: neighborly-api-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborly-api-http
  labels:
    app: neighborly-api-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborly-api-http
  template:
    metadata:
      labels:
        app: neighborly-api-http
    spec:
      containers:
      - name: neighborly-api-http
        image: neighborly-api:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-neighborly-api
        envFrom:
        - secretRef:
            name: neighborly-api
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborly-api-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborly-api
  labels:
    app: neighborly-api
spec:
  selector:
    matchLabels:
      app: neighborly-api
  template:
    metadata:
      labels:
        app: neighborly-api
    spec:
      containers:
      - name: neighborly-api
        image: containersdama.azurecr.io/neighborly-api:1.0.0
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: neighborly-api
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborly-api-function-keys-identity-svc-act
---
# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: neighborly-api
#   labels: {}
# spec:
#   scaleTargetRef:
#     name: neighborly-api
#   triggers:
#   - type: eventgridtrigger
#     metadata:
#       direction: in
#       eventHubName: testhub
#       connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
# ---

